### ISSUE TITLE
Logical Errors in constructing the s3 folder prefix for customer and claims data

### ISSUE THREAD

**Issue by prajwalendra** [aws-samples/amazon-sagemaker-samples#2]
The table names use underscore '_' while the s3 folder uses the hyphen '-'. With the current logic, the #cell 36 stuck in the while loop interrupting in the lab.
The impacted files:
amazon-sagemaker-fraud-detection/Lab_1_and_2-Data-Exploration-and-Features.ipynb
amazon-sagemaker-fraud-detection/scripts/create_dataset.py
/amazon-sagemaker-fraud-detection/scripts/create_feature_store.py

This is hindering the progress of Lab1 and Lab5.

**Comment by mchugh7153** [comment]
Feature store table name is not same as feature group name which is breaking the S3 prefix name. This is due to recent feature store meta data changes.
